recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20231222-152041-nice-billet

language: en


pipeline: 
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer 
  - name: RegexEntityExtractor
   # CRFEntityExtractor is a component used in Rasa Open Source for entity extraction using Conditional Random Fields (CRF) algorithm.
  - name: CRFEntityExtractor
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    entity_recognition: false
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

policies:
 - name: MemoizationPolicy
 - name: TEDPolicy
   max_history: 5
   epochs: 50
   constrain_similarities: true
 - name: RulePolicy